# Workflow to check whether changes to master fulfill all requirements.
name: Status checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
      
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.18

    - name: Run gofmt
      # gofmt does not return non-zero exit codes on failure, so we have to check that there are no issues using grep.
      run: gofmt -d -e . | (! grep ^)

    - name: Run go vet
      run: go vet ./...

    - name: Install ineffassign
      run: go install github.com/gordonklaus/ineffassign@latest

    - name: Run ineffassign
      run: ineffassign ./...

    #- name: Install misspell
    #  run: go install github.com/client9/misspell/cmd/misspell@latest

    # - name: Run misspell
    #   run: misspell -error .

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@2023.1.3
      
    - name: Run staticcheck
      run: staticcheck ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.18

      - name: Run all unit tests
        run: go test -v ./...

  analyze:
    # Require successful test to make sure analysis does not fail on syntax errors.
    needs: test
    uses: ./.github/workflows/codeql-analysis.yml
